env_platform: omarchy

# --------------------------------------------------------------------------------
# Host-level overrides (simple + explicit)
# --------------------------------------------------------------------------------
env_omarchy_pacman_add: []
env_omarchy_pacman_skip: []

env_omarchy_yay_add: []
env_omarchy_yay_skip: []

env_omarchy_script_add: []
env_omarchy_script_skip: []
