env_platform: macos

# --------------------------------------------------------------------------------
# Host-level overrides (simple + explicit)
# --------------------------------------------------------------------------------
env_macos_brew_add: []
env_macos_brew_skip: []

env_macos_cask_add: []
env_macos_cask_skip: []

env_macos_script_add: []
env_macos_script_skip: []
